### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by alphaRed03**
add of exchange of secureshift

### CODE REVIEW

**Comment by h0ek** [comment]
I am not adding guests relinks. I will review this swap and add it in the future. Next time please submit Issue on template "New Service". Thanks.

**Comment by alphaRed03** [comment]
Ok should I need to submit in new service that you will review and add it ?

**Comment by h0ek** [comment]
Nah. I added it to my checklist and will review it tomorrow or on Monday and then I will add it to the list.
Thank you for the submission.

**Comment by alphaRed03** [comment]
Sounds good, thanks!

**Comment by alphaRed03** [comment]
Did you review it ?

**Comment by h0ek** [comment]
It is now listed. Here you can find more details: https://swap.cab/secureshift/

**Comment by alphaRed03** [comment]
Thanks 🤩

**Pull request closed without merging**
